[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer= true
optimizer_runs= 100000
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc_version = "0.8.19"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# [etherscan] 
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# mainnet2 = { key = "ABCDEFG", chain = "mainnet" }
# optimism = { key = "1234567" }
# unknown_chain = { key = "ABCDEFG", url = "<etherscan api url for this chain>" }
