[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer= true
optimizer_runs= 70
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc_version = "0.8.19"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
